#!/bin/sh

VERSION=__PLUGIN_VERSION_PLACEHOLDER__

MAVEN_ARGS="-Dcactus.scope=all \
    -Dcactus.update-root=true \
    -Dcactus.include-root=true \
    com.telenav.cactus:cactus-maven-plugin:${VERSION}:push"

run_maven
