#!/bin/sh

VERSION=__PLUGIN_VERSION_PLACEHOLDER__

mvn \
    -Dcactus.scope=all \
    -Dcactus.update-root=true \
    -Dcactus.include-root=true \
    com.telenav.cactus:cactus-maven-plugin:${VERSION}:push
