#///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#
#  © 2022 Telenav, Inc.
#  Licensed under Apache License, Version 2.0
#
#///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#
# GitHub action that builds code on push or pull request.
#
defaults:
  run:
    shell: bash

name: "Build Release"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'documentation/**'
      - '**/*.md'
    branches:
      - 'release/**'
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - '**/*.md'
    branches:
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set Up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.6

      - name: Configure Git
        run: cd $GITHUB_WORKSPACE && git config --global user.email "nobody@nowhere.com" && git config --global user.name "Nobody"

      - name: Set Up Target Branch
        run: echo 'TARGET_BRANCH='$([ "$GITHUB_EVENT_NAME" = "pull_request" ] && echo "$GITHUB_HEAD_REF" || echo "$GITHUB_REF_NAME") >> $GITHUB_ENV

      - name: Set Up Base Branch
        run: echo 'BASE_BRANCH='$([ "$GITHUB_EVENT_NAME" = "pull_request" ] && echo "$GITHUB_BASE_REF" || echo "develop") >> $GITHUB_ENV

      - name: Set Up Target Commit
        run: echo 'TARGET_COMMIT='$([ "$GITHUB_EVENT_NAME" = "pull_request" ] && echo "$GITHUB_REF" || echo "$GITHUB_SHA") >> $GITHUB_ENV
        
      - name: Set Up Checkout Command
        run: echo 'CHECKOUT_COMMAND='$([ "$GITHUB_EVENT_NAME" = "pull_request" ] && echo "git pull --rebase origin $TARGET_COMMIT" || echo "git checkout $TARGET_COMMIT") >> $GITHUB_ENV

      - name: Clone Telenav-Superpoms
        run: cd $GITHUB_WORKSPACE && git clone "https://github.com/Telenav/telenav-superpom.git" -b $BASE_BRANCH

      - name: Clone Cactus
        run: cd $GITHUB_WORKSPACE && git clone "https://github.com/Telenav/cactus.git" -b $BASE_BRANCH

      - name: Fetch All
        run: cd $GITHUB_WORKSPACE/cactus && git fetch --all

      - name: Ensure Merge Commit Is Available Locally
        run: cd $GITHUB_WORKSPACE/cactus && git fetch origin $GITHUB_REF

      - name: Move Project to Target Ref
        run: cd $GITHUB_WORKSPACE/cactus && echo "Run $CHECKOUT_COMMAND" && eval $CHECKOUT_COMMAND

      - name: List Heads
        run: cd $GITHUB_WORKSPACE/cactus && find .git/refs/heads

      - name: Build Superpoms
        run: cd $GITHUB_WORKSPACE/telenav-superpom && mvn --no-transfer-progress --batch-mode install

      - name: Build Cactus
        run: cd $GITHUB_WORKSPACE/cactus && mvn --no-transfer-progress --batch-mode install
