
name: Publish Snapshot

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Install GPG Secret Key
        run: |
          echo -n "$OSSRH_GPG_SECRET_KEY" | base64 --decode | gpg --batch --import
        env:
          OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

      - name: Publish Snapshot to OSSRH
        env:
          MAVEN_USERNAME: $
          MAVEN_PASSWORD: $
        run: |
          mvn -P attach-jars -P sign-artifacts \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=$ \
            clean deploy
